spring:
  profiles:
    include:
      - secret
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  batch:
    job:
      enabled: false
#      name: analysisAndBuyJob
#      name: sellJob
#      name: checkBalanceJob